import "./globals.css";
import Navigation from "@/component/Navigation";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sania Headquarter Base App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        className={` antialiased flex flex-col justify-between bg-blue-600`}
      >
        <header className="w-full h-[100px] bg-blue-600 items-center flex p-2 text-white">
          <Navigation />
        </header>
        <div className="min-h-[calc(100vh-150px)] bg-gray-300">{children}</div>
        <footer className="h-[50px] bg-blue-600 flex justify-center text-white items-center">
          Copyright
        </footer>
      </body>
    </html>
  );
}
